services:
  mongocfg1:
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    container_name: mongocfg1
    expose:
    - '27017'
    image: mongo
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/mongo_cluster/config1:/data/db
  mongocfg2:
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    container_name: mongocfg2
    expose:
    - '27017'
    image: mongo
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/mongo_cluster/config2:/data/db
  mongocfg3:
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    container_name: mongocfg3
    expose:
    - '27017'
    image: mongo
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/mongo_cluster/config3:/data/db
  mongors1n1:
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    container_name: mongors1n1
    expose:
    - '27017'
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/mongo_cluster/data1:/data/db
  mongors1n2:
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    container_name: mongors1n2
    expose:
    - '27017'
    image: mongo
    ports:
    - 27027:27017
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/mongo_cluster/data2:/data/db
  mongors1n3:
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    container_name: mongors1n3
    expose:
    - '27017'
    image: mongo
    ports:
    - 27037:27017
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/mongo_cluster/data3:/data/db
  mongors2n1:
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    container_name: mongors2n1
    expose:
    - '27017'
    image: mongo
    ports:
    - 27047:27017
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/mongo_cluster/data4:/data/db
  mongors2n2:
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    container_name: mongors2n2
    expose:
    - '27017'
    image: mongo
    ports:
    - 27057:27017
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/mongo_cluster/data5:/data/db
  mongors2n3:
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    container_name: mongors2n3
    expose:
    - '27017'
    image: mongo
    ports:
    - 27067:27017
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/mongo_cluster/data6:/data/db
  mongos1:
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017
      --port 27017
    container_name: mongos1
    depends_on:
    - mongocfg1
    - mongocfg2
    expose:
    - '27017'
    image: mongo
    ports:
    - 27019:27017
    volumes:
    - /etc/localtime:/etc/localtime:ro
  mongos2:
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017
      --port 27017
    container_name: mongos2
    depends_on:
    - mongocfg1
    - mongocfg2
    expose:
    - '27017'
    image: mongo
    ports:
    - 27020:27017
    volumes:
    - /etc/localtime:/etc/localtime:ro
version: '3.0'
